name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}" > .env
      - name: Sign in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t rommaniitedomum/front .
      - name: Push Docker Image
        run: docker push rommaniitedomum/front:latest

 deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Pull image from Docker Hub and deploy to EC2
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "${SSH_KEY}" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ${SSH_USER}@${AWS_HOST} << 'EOF'
          docker pull rommaniitedomum/front:latest
          docker rm -f reactContainer || true
          docker run -d -p 80:80 --name reactContainer rommaniitedomum/front
        EOF
